[CP-42] Saisir les identifiants d’inscription
ValbionGroup/Comus-Party pull request #20
Opened 2024-11-13 11:07 UTC by nzoEtd

2024-11-14 15:49 UTC, CarteSD requested changes

2024-11-14 15:49 UTC, CarteSD commented on src/controllers/controllerUser.class.php
Tout ça peut juste aller dans le fichier `controllerAuth.class.php` qui gère l'authentification (connexion & inscription)

2024-11-14 15:49 UTC, CarteSD commented on src/models/user.dao.php
> +        $stmtUser->bindParam("ss", $email, $password);
Idem que tout à l'heure, à voir par les autres reviewers.
```
$stmtUser = $this->pdo->prepare("INSERT INTO " . DB_PREFIX . "user (email, password, email_verified_at, email_verify_token, disabled) VALUES (:email, :password, null, null, 0)");
        $stmtUser->bindParam(":email", $email);
        $stmtUser->bindParam(":password", $password);
```

2024-11-14 15:49 UTC, CarteSD commented on assets/css/builded.css
Il ne devrait pas y avoir ce fichier

2024-11-14 15:49 UTC, CarteSD commented on src/controllers/controllerUser.class.php
> +require_once 'C:/wamp64/www/Comus-Party/src/models/player.dao.php';
Inutile si l'autoload fonctionne bien (théoriquement)

2024-11-14 15:49 UTC, CarteSD commented on src/models/player.dao.php
> +        $stmtPlayer->bindParam("sss", $uuid, $username, $userId);
Comment le `bindParam` fonctionne ?
Dans le cas où ça fonctionne, je ne trouve pas ça clair du tout et je ferais plutôt :
```
$stmtPlayer = $this->pdo->prepare("INSERT INTO " . DB_PREFIX . "player (uuid, username, user_id) VALUES (:uuid, :username, :user_id)");
        $stmtPlayer ->bindParam(":uuid", $uuid);
        $stmtPlayer ->bindParam(":username", $username);
        $stmtPlayer ->bindParam(":user_id", $userId);
```

2024-11-14 15:49 UTC, CarteSD commented on src/models/user.dao.php
> +    }
Cette méthode ressemble très fortement à la méthode `findByEmail()`, seul le résultat retourné change.
Je pense qu'il serait mieux d'utiliser un `findByEmail()` et retourner un `is_null(findByEmail($email))`

Ou alors, cette méthode ne faisant que deux lignes, directement implémenter ces deux lignes à l'endroit où la vérification de l'existence de cet utilisateur est nécessaire.

2024-11-14 15:49 UTC, CarteSD commented on src/models/user.dao.php
> +                                        JOIN " . DB_PREFIX . "player p ON u.id = p.user_id
À quoi sert la jointure ?

2024-11-14 15:49 UTC, CarteSD commented on src/models/user.dao.php
> +    public function userExists(?string $email)
Préciser ce que la méthode retourne

2024-11-14 15:49 UTC, CarteSD commented on src/models/user.dao.php
> +    }
Idem qu'au dessus, je pense que tu peux utiliser un `findByEmail()` et grâce à l'objet que la méthode te retourne, simplement faire un `getId()` me semblerait plus cohérent.
Et encore une fois, à voir si le fait de créer une méthode pour ça vaut vraiment le coup ou pas.

2024-11-14 15:49 UTC, CarteSD commented on src/models/player.dao.php
> +    }
Je pense que faire une méthode `findByUsername()` serait plus générique et pourrait donc être utilisé dans d'autres code plus tard.
Et à partir de là, soit implémenter dans cette méthode un appel à la fonction `findByUsername()` et ensuite une vérification avec un `is_null()` ou alors directement exécuter ces deux lignes à l'endroit où c'est nécessaire.

2024-11-14 15:49 UTC, CarteSD commented on src/models/player.dao.php
> +    }
Par exemple, le fait de créer une méthode `findByUsername()` comme dit précédemment, permettrait de ne pas avoir cette requête presque identique à la base de données qui se répète et donc d'utiliser le `getId()` sur l'objet que retourne la méthode appelée précédemment.

2024-11-14 15:49 UTC, CarteSD commented on src/models/player.dao.php
> +                                            WHERE p.username = ?");
**VOIR LE COMMENTAIRE EN DESSOUS AVANT DE MODIFIER CETTE REQUÊTE**

La requête peut être simplifiée car la jointure est selon moi totalement inutile.
Un simple`"SELECT * FROM " . DB_PREFIX . "player WHERE username = :username");` ferait largement le travail

2024-11-14 15:49 UTC, CarteSD commented on src/templates/authenticationTemplate.twig
On a déjà une template d'authentification, à voir avec Lucas (qui l'a faite), laquelle correspond le mieux aux attentes.

2024-11-14 15:49 UTC, CarteSD commented on src/templates/signUp.twig
Je ne peux pas voir si la page fonctionne correctement car certaines inclusions renvoient un message d'erreur :
```
Warning: require_once(C:/wamp64/www/Comus-Party/src/models/user.class.php): Failed to open stream: No such file or directory in C:\xampp\htdocs\Comus-Party\src\controllers\controllerUser.class.php on line 13

Fatal error: Uncaught Error: Failed opening required 'C:/wamp64/www/Comus-Party/src/models/user.class.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\Comus-Party\src\controllers\controllerUser.class.php:13 Stack trace: #0 C:\xampp\htdocs\Comus-Party\include.php(23): require_once() #1 C:\xampp\htdocs\Comus-Party\public\index.php(6): require('C:\\xampp\\htdocs...') #2 {main} thrown in C:\xampp\htdocs\Comus-Party\src\controllers\controllerUser.class.php on line 13
```

2024-11-14 16:03 UTC, lucas-luchack commented on assets/css/builded.css
👍🏻

2024-11-14 16:05 UTC, lucas-luchack commented on src/controllers/controllerUser.class.php
👍🏻

2024-11-14 16:05 UTC, lucas-luchack commented on src/controllers/controllerUser.class.php
> +require_once 'C:/wamp64/www/Comus-Party/src/models/player.dao.php';
```suggestion
```

2024-11-14 16:32 UTC, lucas-luchack commented on src/models/user.dao.php
> +     * @details La méthode crée un utilisateur dans la base de données, en fonction des paramètres passés.
```suggestion
     * @details La méthode créée un utilisateur dans la base de données, en fonction des paramètres passés.
```

2024-11-14 16:34 UTC, lucas-luchack commented on src/models/user.dao.php
> +    }
L'implémentation d'une méthode intérmédiaire est plus pertinante dans le cas d'une réutilisation plus tard

2024-11-14 16:35 UTC, lucas-luchack commented on src/routes.php
> +    ControllerFactory::getController("user", $loader, $twig)->call("register");
Tu pourrais passer en paramètre de `register` les informations

2024-11-14 16:36 UTC, lucas-luchack commented on src/templates/authenticationTemplate.twig
C'est effectivement répétitif.
De plus, ce fichier n'est pas placé au bon endroit.

2024-11-14 16:42 UTC, lucas-luchack commented on assets/img/authentication_img/placeholder.png
Pourquoi ce ficher + il n'est pas au bon endroit

2024-11-14 16:43 UTC, lucas-luchack commented on .gitignore
> +builded.css
A ne pas modifier

2024-11-14 16:43 UTC, lucas-luchack commented on assets/css/builded.css
Ne dois pas être push

2024-11-14 16:45 UTC, lucas-luchack commented on src/auth/signUpCheck.php
Pourquoi garder un fichier entièrement commenté ???

2024-11-14 16:48 UTC, lucas-luchack commented on src/templates/accueil.twig
Ce fichier peut être supprimé

2024-11-15 11:20 UTC, CarteSD requested changes

2024-11-15 11:20 UTC, CarteSD commented on src/models/player.dao.php
> +        // $player->getStatistics()->setGamesHosted($data['games_hosted']);
Vérifier si les attributs existent, sinon mettre à 0

2024-11-15 11:20 UTC, CarteSD commented on src/models/player.dao.php
> +        $stmtPlayer->bindParam(3, $userId);
$stmtPlayer->bindParam(:uuid, $uuid);

2024-11-15 11:20 UTC, CarteSD commented on src/models/user.dao.php
> +            $stmtUser->bindParam(1, $email);
:email

2024-11-15 11:20 UTC, CarteSD commented on src/templates/signUp.twig
Gestion thème sombre / clair

2024-11-15 11:20 UTC, CarteSD commented on src/templates/signUp.twig
Je n'arrive pas à m'inscrire

2024-11-15 11:21 UTC, lucas-luchack requested changes

2024-11-15 11:21 UTC, lucas-luchack commented on assets/css/builded.css
Même commentaire.

2024-11-15 11:21 UTC, lucas-luchack commented on public/assets/js/authentication.js
> +}
Pourquoi envoyer au format JSON.
Le message devrait s'afficher avec les classes tailwinds...

2024-11-15 11:21 UTC, lucas-luchack commented on src/controllers/controllerAuth.class.php
> +        $data = json_decode(file_get_contents("php://input"), true);
Voir mon commentaire précédent

2024-11-15 11:21 UTC, lucas-luchack commented on src/models/player.dao.php
>          $player->setUserId($data['user_id']);
Cela impacte d'autres fonctions non ?

2024-11-15 11:21 UTC, lucas-luchack commented on src/models/player.dao.php
> +
```suggestion
```

2024-11-15 11:21 UTC, lucas-luchack commented on src/models/user.dao.php
> +            $stmtUser->bindParam(2, $password);
Il faut créer un token pour l'e-mail ou (plus propre) appeler une fonction qui génère un token le renvoi pour être mis en bd et envoie le mail de confirmation.

2024-11-15 11:21 UTC, lucas-luchack commented on src/routes.php
> +    ControllerFactory::getController("auth", $loader, $twig)->call("register");
Tu peux passer des paramètres à ta fonction, cela sera plus propre que l'envoi de json etc

2024-11-20 17:54 UTC, CarteSD requested changes
Je n'ai rien compris à la structure de ton code.

J'ai dû arrêter de lire à un certain moment, car rien n'est documenté, certaines méthodes sont appelées mais n'existent pas, et d'autres sont appelées, mais via le mauvais contrôleur.

Un contrôleur à du code écrit en dehors de lui-même, et qui l'appelle récursivement.

Lors de la vérification de l'e-mail, comment récupérer le token en POST alors que l'utilisateur à cliqué sur un lien, donc GET ?

2024-11-20 17:54 UTC, CarteSD commented on public/assets/js/authentication.js
> +
Documenter l'entête du fichier

2024-11-20 17:54 UTC, CarteSD commented on public/assets/js/authentication.js
> +    //     sendAuthData(); });
Enlever ça ?

2024-11-20 17:54 UTC, CarteSD commented on public/assets/js/authentication.js
> +// }
Enlever tout ça si c'est inutile

2024-11-20 17:54 UTC, CarteSD commented on src/auth/signUpCheck.php
Supprimer le fichier plutôt que le laisser tout commenté

2024-11-20 17:54 UTC, CarteSD commented on src/controllers/controllerVerifEmail.class.php
Tout ça peut aller avec le `controllerAuth` déjà existant, puisque ça gère l'authentification

2024-11-20 17:54 UTC, CarteSD commented on src/models/user.dao.php
> +
Documentation

2024-11-20 17:54 UTC, CarteSD commented on src/controllers/controllerVerifEmail.class.php
Manque la documentation de toutes les méthodes

2024-11-21 10:52 UTC, lucas-luchack requested changes

2024-11-21 10:52 UTC, lucas-luchack commented on public/assets/js/authentication.js
> +}
Permettre l'affichage de toutes les conditions non remplies à la fois et pas une par une.

2024-11-21 10:52 UTC, lucas-luchack commented on public/assets/js/authentication.js
> +}
Permettre l'affichage de toutes les conditions non remplies à la fois et pas une par une.

2024-11-21 10:52 UTC, lucas-luchack commented on src/controllers/controllerAuth.class.php
> +                $verificationLink = "/verifyEmail?token=$emailVerifToken";
Utiliser une réelle route du contrôleur pour ça
```suggestion
                $verificationLink = "/verify-email/$emailVerifToken";
```

2024-11-21 10:52 UTC, lucas-luchack commented on src/controllers/controllerAuth.class.php
> +                mail($email, $subject, $message);
Il faudra modifier le contenu du mail pour respecter nôtre charte graphique. Ajouter un TODO pour ne pas oublier. 
On utilisera SMTP avec les paramètres présent dans la conf et non la fonction mail de PHP.

2024-11-21 10:52 UTC, lucas-luchack commented on src/controllers/controllerAuth.class.php
> +        unset($_SESSION['resultMessage']);
???

Pourquoi mettre en session puis enlever la seconde d'après ?

2024-11-21 10:52 UTC, lucas-luchack commented on src/controllers/controllerAuth.class.php
> +            elseif($existingUser && !$existingPlayer) { $resultMessage = "Création de l'utilisateur échouée (email existant)"; }
On pourra même vérifier en Ajax avant l'envoi du formulaire. (_Mais c'est un plus_)

2024-12-03 18:43 UTC, CarteSD commented
![image](https://github.com/user-attachments/assets/1246418b-37a7-4d00-8cbb-19bda5aa2eeb)

Dans le cas où l'e-mail existe déjà (et je suppose que c'est pareil pour le nom d'utilisateur, je pense qu'on peut faire un truc un peu plus esthétique, 2 possibilités :
   - Utilisation de la méthode `addExceptionParametersToTwig` de la classe `ErrorHandler` _(il faut que tu refasses un petit merge de la branche main dans la tienne car tu n'as pas cette classe)_, qui permet ensuite que l'erreur soit gérée par la template `base.twig`
   - Gérer toi-même le message d'une autre manière, en l'affichant au niveau du champ de saisi de celui posant problème

2024-12-03 18:50 UTC, CarteSD requested changes

2024-12-03 18:50 UTC, CarteSD commented on src/controllers/controllerAuth.class.php
> +        if(session_status() === PHP_SESSION_NONE) { session_start(); }
Normalement, comme on a une instruction `session_start()` dans le fichier `include.php`, cette vérification n'est pas utile.

2024-12-03 18:50 UTC, CarteSD commented on src/controllers/controllerAuth.class.php
> +                        '<p>Vous avez créer un compte sur le site Comus.</p>
```suggestion
                        '<p>Vous avez créer un compte sur le site Comus Party.</p>
```

2024-12-03 18:50 UTC, CarteSD commented on src/templates/signUp.twig
Modifier l'agencement des messages d'erreurs dus aux saisis + dus à la vérification côté serveur (Cf les deux commentaires que j'ai fais directement dans le fil de discussion de la PR)

2024-12-03 19:04 UTC, CarteSD commented on src/controllers/controllerAuth.class.php
Il faut ajouter le `namespace ComusParty\Controllers;`, c'est bizzare qu'il n'aparraisse pas dans les modifications alors qu'il est sur la branche main

2024-12-03 19:14 UTC, CarteSD commented on src/controllers/controllerAuth.class.php
> +                    $mail->Subject = 'Confirmation de votre compte Comus Party' . MAIL_BASE; // Sujet du message
```suggestion
                    $mail->Subject = 'Confirmation de votre compte' . MAIL_BASE; // Sujet du message
```

2024-12-03 19:15 UTC, CarteSD commented on src/controllers/controllerAuth.class.php
> +                    $mail->Subject = 'Confirmation de votre compte Comus Party' . MAIL_BASE; // Sujet du message
Sinon ça fait "Confirmation de votre compte Comus Party | Comus Party", donc répétition inutile à mon goût

2024-12-04 07:30 UTC, lucas-luchack commented on src/controllers/controllerAuth.class.php
> +        if(session_status() === PHP_SESSION_NONE) { session_start(); }
En soit si, au cas où

2024-12-04 07:42 UTC, lucas-luchack requested changes

2024-12-04 07:42 UTC, lucas-luchack commented on src/controllers/controllerAuth.class.php
> +                        <a href="http://localhost:8000/confirm-email/' . urlencode($emailVerifToken) . '"><button>Confirmer mon compte</button></a>';
Ne pas oublier que cette url ne marche que sur ton pc. 
Il faut utiliser la variable d'environnement `BASE_URL`

```suggestion
                        <a href="' . $BASE_URL . '/confirm-email/' . urlencode($emailVerifToken) . '"><button>Confirmer mon compte</button></a>';
```

2024-12-04 07:42 UTC, lucas-luchack commented on src/controllers/controllerAuth.class.php
> +                        http://localhost:8000/confirm-email/' . urlencode($emailVerifToken);
Idem ici

2024-12-04 07:42 UTC, lucas-luchack commented on src/templates/confirmEmail.twig
Il faudra voir pour améliorer cette page, ou, s'en passer. 

_Pas nécessaire pour cette PR_

2024-12-04 08:16 UTC, lucas-luchack requested changes

2024-12-04 08:16 UTC, lucas-luchack commented on src/templates/signUp.twig
Utiliser la classe input et btn pour les champ et les boutons

2024-12-08 10:15 UTC, CarteSD requested changes

2024-12-08 10:15 UTC, CarteSD commented on src/controllers/controllerAuth.class.php
> +                        '<p>Vous avez créer un compte sur Comus Party.</p>
```suggestion
                        '<p>Vous avez créé un compte sur Comus Party.</p>
```

2024-12-08 10:15 UTC, CarteSD commented on src/controllers/controllerAuth.class.php
> +                        'Vous avez créer un compte sur Comus Party.
```suggestion
                        'Vous avez créé un compte sur Comus Party.
```

2024-12-09 10:53 UTC, CarteSD commented
![image](https://github.com/user-attachments/assets/c4639575-e5d6-4e19-a49a-7d5438c1e26b)

Le formulaire ne fait pas toute la largeur, j'ai pas regardé dans le code ce qui fait ça, mais du coup il faudrait l'enlever

2024-12-10 13:17 UTC, CarteSD requested changes

2024-12-10 13:17 UTC, CarteSD commented on src/Controllers/controllerAuth.class.php
> +        $_SESSION['resultMessage'] = $resultMessage;
À quoi sert cette variable de session ?

2024-12-10 13:17 UTC, CarteSD commented on src/Controllers/controllerAuth.class.php
> +        echo $twig->render('signUp.twig', ['resultMessage' => $resultMessage]);
Je pense qu'il serait mieux de lever une exception plutôt que créé un simple message que tu passes en variables Twig.

Et étant donné (qu'une fois que ma PR sera validée), il y aura la gestion d'exception par la méthode `call()`, tu auras simplement a ajouter ton exception dans le switch.

2024-12-10 13:24 UTC, CarteSD requested changes

2024-12-10 13:24 UTC, CarteSD commented on src/Controllers/controllerAuth.class.php
> +    }
Je pense qu'il serait bien d'utiliser la classe `Validator` pour faire la vérification des champs du formulaire.

2024-12-10 13:24 UTC, CarteSD commented on src/Controllers/controllerAuth.class.php
> +    }
Je pense qu'il serait bien d'utiliser la classe `Validator` pour faire la vérification des champs du formulaire ainsi que de concaténer les expressions régulières en une seule

2024-12-10 13:24 UTC, CarteSD commented on src/Controllers/controllerAuth.class.php
> +    }
Je pense qu'il serait bien d'utiliser la classe `Validator` pour faire la vérification des champs du formulaire.

2024-12-13 08:24 UTC, lucas-luchack requested changes
Je n'ai pas tester le code @CarteSD s'en occupe.
Mais sinon ça me semble correct.

2024-12-13 08:24 UTC, lucas-luchack commented on src/Controllers/controllerAuth.class.php
> +        echo $twig->render('signUp.twig', ['confirmationResult' => $confirmationResult]);
Si l'e-mail est confirmé, **rediriger** sur la page de login, pas sur celle de création de compte

2024-12-14 11:00 UTC, CarteSD requested changes

2024-12-16 14:12 UTC, CarteSD requested changes

2024-12-16 14:12 UTC, CarteSD commented on src/templates/signUp.twig
> +                <label for="privacyPolicy">J'accepte la <a href="/privacy-policy" class="text-night-2 dark:text-lavender-blush-2 hover:underline transition-all ease-in-out">politique de confidentiali
```suggestion
                <label for="privacyPolicy">J'accepte la <a href="/privacy-policy" class="text-night-2 dark:text-lavender-blush-2 font-semibold hover:underline transition-all ease-in-out">politique de confidentialité</a></label>
```

2024-12-16 14:12 UTC, CarteSD commented on src/templates/signUp.twig
> +                <label for="termsOfService">J'accepte les <a href="/terms-of-service" class="text-night-2 dark:text-lavender-blush-2 hover:underline transition-all ease-in-out">conditions d'utilisati
```suggestion
                <label for="termsOfService">J'accepte les <a href="/terms-of-service" class="text-night-2 dark:text-lavender-blush-2 font-semibold hover:underline transition-all ease-in-out">conditions d'utilisation</a></label>
```

2024-12-16 14:12 UTC, CarteSD commented on src/templates/signUp.twig
Au niveau des case à cocher, faire un div dans laquelle il y a 2 sous-div, ce qui permet de réduire l'espace entre les deux sous-div qui actuellement est très grand.

Il y a un problème d'overflow-y aussi.

Essayer de styliser un peu la cas à cocher aussi ?

2024-12-16 18:16 UTC, lucas-luchack commented
Avant que l'on review, résous les conflits

2024-12-17 08:34 UTC, CarteSD commented
Lorsque je clique sur le bouton envoyé par e-mail, je suis redirigé sur la page d'inscription et la vérification en base de données ne se met pas à jour

2024-12-17 08:34 UTC, CarteSD commented
Ajouter un message avec le MessageHandler pour dire qu'un e-mail de confirmation de compte a été envoyé

2024-12-17 08:35 UTC, CarteSD requested changes
Lorsque je clique sur le bouton envoyé par e-mail, je suis redirigé sur la page d'inscription et la vérification en base de données ne se met pas à jour

Ajouter un message avec le MessageHandler pour dire qu'un e-mail de confirmation de compte a été envoyé

2024-12-17 15:03 UTC, CarteSD requested changes
Je veux une croix pour les checkbox + aligné à gauche

2024-12-18 08:24 UTC, CarteSD requested changes
Possible de mettre le fond des checkbox en blue-violet-base ? Je pense que ça coïnciderait mieux avec le bouton qui est en dessous

Et il n'y a toujours pas de scroll

2024-12-18 15:19 UTC, ConchezRob requested changes

2024-12-18 15:19 UTC, ConchezRob commented on src/templates/signUp.twig
Si l'utilisateur fait une erreur sur chaque input, le titre 'Inscription' part au paradis et le lien pour aller vers la page de connexion va en enfer.

2024-12-18 15:19 UTC, ConchezRob commented on src/templates/signUp.twig
Si l'utilisateur rentre son mot de passe dans l'input prévu à cette effet, qu'il clique ailleurs et reclique sur ce dernier, il ne peut plus voir son mot de passe.

2024-12-18 17:10 UTC, nzoEtd commented on src/templates/signUp.twig
Réglé rien qu'pour toi mon Robinou

2024-12-18 20:32 UTC, CarteSD requested changes
Change
T'as cru sale fou

2024-12-18 22:43 UTC, ConchezRob commented on src/templates/signUp.twig
Enzo la big sasa

2024-12-19 07:38 UTC, CarteSD approved these changes

2024-12-19 07:38 UTC, CarteSD commented on src/templates/signUp.twig
Les champs sont cut sur le côté un peu

2024-12-19 08:20 UTC, CarteSD submitted a review, later dismissed

2024-12-20 10:16 UTC, lucas-luchack requested changes
**La page ne fonctionne toujours pas.**

- Multiples erreurs PHP levées
- La vérification des champs côté client (*js*) n'empêche pas l'envoi du formulaire au serveur
- Si la saisie n'est pas correcte, les données sont quand même envoyées avec un message de succès
- ...

Je n'ai pas tout testé dû au fait de ces problèmes qui doivent être résolu avant tout.

2024-12-20 10:16 UTC, lucas-luchack commented on src/Controllers/controllerAuth.class.php
> +        header('Location: /login');
```suggestion
        header('Location: /login');
        exit;
```

2024-12-20 10:16 UTC, lucas-luchack commented on src/routes.php
> +    if (isset($_POST['email']) && isset($_POST['password'])) {
Il n'y a que ces données la a vérifier ?

2024-12-20 10:16 UTC, lucas-luchack commented on src/routes.php
>  });
```suggestion
}, 'guest');
```

2024-12-20 10:16 UTC, lucas-luchack commented on src/templates/layouts/authentification.twig
> -        <div class="h-1/2 sm:h-full w-full sm:w-1/2 p-16 bg-auth-background">
Pourquoi l'enlever (j'en sais vrm rien donc bon)

2024-12-24 09:10 UTC, CarteSD requested changes
Dans le cas où je m'inscris avec une adresse e-mail déjà en base de données, ça me met le message de confirmation comme quoi mon compte a été créé et j'ai reçu un e-mail, mais ça n'envoi rien.

À voir avec les autres si c'est bien ou pas :
 - niveau sécurité, ça permet qu'un mec ne puisse pas savoir si un compte existe avec l'adresse e-mail qu'il founit
 - niveau "accessibilité", si le mec ne sait pas qu'il a déjà un compte, il va galérer à connaître le problème

2024-12-28 11:09 UTC, CarteSD commented
Si l'adresse e-mail et / ou le nom d'utilisateur sont déjà pris, il faudrait plutôt redirigé sur la page d'inscription.
Et même si possible plutôt faire du Ajax qui indique directement, au moment de la saisi, si c'est déjà pris (ce qui évite d'avoir besoin de tout refaire du au refresh de la page)

2024-12-28 11:10 UTC, CarteSD requested changes
Si l'adresse e-mail et / ou le nom d'utilisateur sont déjà pris, il faudrait plutôt redirigé sur la page d'inscription.

Et même si possible plutôt faire du Ajax qui indique directement, au moment de la saisi, si c'est déjà pris (ce qui évite d'avoir besoin de tout refaire du au refresh de la page)

+ je ne vois pas trop l'utilité sur bouton "Reset", je n'ai jamais vu ça sur un formulaire d'inscription

2025-01-02 21:45 UTC, lucas-luchack approved these changes

2025-01-02 21:45 UTC, lucas-luchack commented on src/templates/signUp.twig
Je ne trouve pas l'affichage de l'oeil utile, mais il ne s'agit que la que d'une préfèrence personelle.

2025-01-03 11:03 UTC, CarteSD approved these changes
https://github.com/ValbionGroup/Comus-Party/pull/20#pullrequestreview-2524699916

Voir tout de même pour essayer de faire du AJAX dans le futur

2025-01-06 12:50 UTC, ConchezRob approved these changes

2025-01-07 07:31 UTC, merged