[CP-5] Voir son panier
ValbionGroup/Comus-Party pull request #24
Opened 2024-11-14 07:28 UTC by TistouCode

2024-11-14 14:21 UTC, TistouCode commented on src/templates/basket.twig
> +    <div class="w-full flex">
yes merci t'es un bon

2024-11-14 14:22 UTC, TistouCode commented on src/templates/basket.twig
> +        <div class="flex flex-col w-1/3 h-72 mt-5 ml-5 mr-5">
merci c'est fait, j'ai juste fait en sorte que la taille de la div soit plus grande

2024-11-14 14:36 UTC, CarteSD submitted a review, later dismissed

2024-11-14 15:57 UTC, lucas-luchack requested changes

2024-11-14 15:57 UTC, lucas-luchack commented on src/controllers/controllerBasket.class.php
> +     * Constructeur de la classe ControllerBasket
```suggestion
     * @brief Constructeur de la classe ControllerBasket
```

2024-11-14 15:57 UTC, lucas-luchack commented on src/templates/basket.twig
> +            <h2 class="font-semibold text-xl mb-3">Panier</h2>
Toujours pas présente. Comme sur la page boutique où elle n'est pas.

2024-11-14 15:57 UTC, lucas-luchack commented on src/templates/basket.twig
> +            <h2 class="font-semibold text-xl mb-3">Panier</h2>
```suggestion
<h2 class="font-semibold text-xl mb-3 font-serif">Panier</h2>
```

2024-11-15 08:22 UTC, CarteSD approved these changes

2024-11-21 10:43 UTC, CarteSD commented on src/controllers/controllerShop.class.php
> + */
Il y a deux fois la documentation du fichier ?

2024-11-21 11:03 UTC, lucas-luchack approved these changes

2024-11-27 13:07 UTC, CarteSD requested changes

2024-11-27 13:07 UTC, CarteSD commented on src/controllers/controllerShop.class.php
>  class ControllerShop extends Controller {
Pourquoi t'as supprimé la documentation ?

2024-11-28 07:31 UTC, lucas-luchack requested changes

2024-11-28 07:31 UTC, lucas-luchack commented on src/controllers/controllerShop.class.php
```suggestion

/**
 * @brief Classe ControllerShop
 * @details La classe ControllerShop permet de gérer les actions liées à un article
 */
```

2024-11-28 07:31 UTC, lucas-luchack submitted a review, later dismissed

2024-11-28 16:56 UTC, CarteSD approved these changes

2024-11-28 16:56 UTC, merged