[CP-8] Se connecter
ValbionGroup/Comus-Party pull request #33
Opened 2024-11-15 10:18 UTC by CarteSD

Ajout de l'obligation d'être connecté afin de pouvoir accéder à toutes les pages (hormis la page de login)

2024-11-15 10:24 UTC, nzoEtd approved these changes
Approuvé après suggestion de ne pas rediriger vers login pour la page register

2024-11-15 10:28 UTC, lucas-luchack commented on src/routes.php
> +    }
```suggestion
```

2024-11-15 10:29 UTC, lucas-luchack submitted a review, later dismissed

2024-11-15 10:33 UTC, nzoEtd commented on src/routes.php
>  });
J'comprends p't'être mal mais ça veut dire qu'on est obligé d'être connecté pour être sur l'site?

2024-11-15 10:40 UTC, ConchezRob submitted a review, later dismissed

2024-11-15 10:52 UTC, nzoEtd submitted a review, later dismissed

2024-11-15 10:58 UTC, lucas-luchack requested changes

2024-11-15 10:58 UTC, lucas-luchack commented on tests/ControllerAuthTest.php
> +    public function testAuthenticateOnNullEmailAndPassword(): void
Problème de nom de fonction

2024-11-15 10:58 UTC, lucas-luchack commented on tests/ControllerAuthTest.php
> +}
Peut être intéressant de rajouter un test quand l'e-mail n'est pas nul mais n'est pas valide

2024-11-18 07:45 UTC, ConchezRob approved these changes

2024-11-18 07:46 UTC, merged