[CP-4] Ajouter un article à son panier
ValbionGroup/Comus-Party pull request #35
Opened 2024-11-15 11:09 UTC by TistouCode

2024-11-18 08:15 UTC, lucas-luchack requested changes

2024-11-18 08:15 UTC, lucas-luchack commented on public/assets/js/basket.js
> +            alert(xhr.responseText);  // Affiche la réponse (par exemple : "Article ajouté au panier !")
Ne pas utiliser un alert.
Faire un message propre sur l'interface.

2024-11-18 08:15 UTC, lucas-luchack commented on public/assets/js/basket.js
> +            location.reload()
Si on supprime un seul élément et qu'il en reste, on ne veut pas que la page soit reload.
Le `document.getElementById("eltPanier").style.display = "none";` ne supprime pas tous les éléments ?

2024-11-18 08:15 UTC, lucas-luchack commented on public/assets/js/shop.js
L'uilisation de Doxygen peut être appliqué sur ce fichier aussi

2024-11-18 08:15 UTC, lucas-luchack commented on public/assets/js/shop.js
> +function showModale(article){
```suggestion
function showModal(article) {
```

2024-11-18 08:15 UTC, lucas-luchack commented on public/assets/js/shop.js
> +                alert(xhr.responseText);  // Affiche la réponse (par exemple : "Article ajouté au panier !")
Idem, utilisation d'un alert c'est **très très moche**

2024-11-18 08:15 UTC, lucas-luchack commented on src/models/article.class.php
> +    private ?string $type;
Pourquoi ce changement ?
_Beaucoup plus propre avec un type PHP !_

2024-11-18 08:15 UTC, lucas-luchack commented on src/models/article.dao.php
> +    function findArticlesWithIds($ids)
Il n'y avait pas une fonction similaire mais qui n'en retourne qu'un ?

A  voir avec les autres ce qu'ils préfèrent.

2024-11-18 08:15 UTC, lucas-luchack commented on src/models/article.dao.php
> +            $type = "Banner";
Ne pas changer, plus propre avec un type PHP

2024-11-18 08:15 UTC, lucas-luchack commented on src/routes.php
> +    throw new Exception("Merci de renseigner une adresse e-mail et un mot de passe valides");
???

2024-11-18 08:15 UTC, lucas-luchack commented on src/templates/basket.twig
> +                    <span>0€</span>
Calcul du prix ?

2024-11-20 11:16 UTC, CarteSD requested changes

2024-11-20 11:16 UTC, CarteSD commented on src/controllers/controllerShop.class.php
> +//        var_dump($banners);
Enlever les commentaires

2024-11-20 11:16 UTC, CarteSD commented on src/models/article.dao.php
> +    function findArticlesWithIds($ids)
C'est quoi le type du paramètre ?

2024-11-20 11:16 UTC, CarteSD commented on src/models/article.dao.php
> +    function findArticlesWithIds($ids)
Manque la documentation

2024-11-20 11:16 UTC, CarteSD commented on src/models/article.dao.php
Voir s'il est pas plus judicieux de faire une méthode `findAllByType()` puisque le code des deux méthodes de recherche selon le type est strictement identique

2024-11-20 11:16 UTC, CarteSD commented on src/templates/shop.twig
> +                                 onclick="showModale({ id : '{{ banner.id }}',  name : '{{ banner.name }}', description : '{{ banner.description }}', pricePoint : '{{ banner.pricePoint }}', priceEuro
`showModal()`

2024-11-20 11:16 UTC, CarteSD commented on src/templates/shop.twig
> +                                 onclick="showModale({ id : '{{ pfp.id }}', name : '{{ pfp.name }}', description : '{{ pfp.description }}', pricePoint : '{{ pfp.pricePoint }}', priceEuro : '{{ pfp.pr
`showModal()`

2024-11-21 10:31 UTC, CarteSD requested changes

2024-11-21 10:31 UTC, CarteSD commented on src/controllers/controllerBasket.class.php
> +        }
On a le prix en €, mais il n'y a pas de prix en Comus Coin

2024-11-21 10:31 UTC, CarteSD commented on src/controllers/controllerBasket.class.php
> +
Enlever tous les retours à la ligne inutiles.
En laisse pour aérer le code, mais trop d'espace entre chaque ligne casse la fluidité de la compréhension du programme je trouve

2024-11-21 10:31 UTC, CarteSD commented on src/controllers/controllerBasket.class.php
> +            // Ajouter l'ID de l'article au panier s'il n'y est pas déjà
On l'ajoute ou on le supprime ?

2024-11-21 10:31 UTC, CarteSD commented on src/controllers/controllerBasket.class.php
> +                $article = $managerArticle->findArticlesWithIds( array($id_article) );
On passe un tableau avec un seul élément ? Il n'y a pas une méthode `findById()` qui retourne qu'un seul objet de type `Article` ?

2024-11-21 10:31 UTC, CarteSD commented on src/controllers/controllerBasket.class.php
> +//                echo "Article supprimé du panier !";
Supprimer le commentaire

2024-11-21 10:31 UTC, CarteSD commented on src/controllers/controllerBasket.class.php
> +//                echo "L'article n'est pas dans le panier.";
Supprimer le commentaire

2024-11-21 10:31 UTC, CarteSD commented on src/controllers/controllerShop.class.php
> +    function addBasket()
Je trouve le nom un peu flou, même s'il y a effectivement la documentation, je pensais que c'était pour ajouter un panier ?
Peut être mettre un `addArticleToBasket()` ou juste un `addToBasket()` ?

2024-11-21 10:31 UTC, CarteSD commented on src/controllers/controllerShop.class.php
La méthode pour ajouter un article au panier est dans `controllerShop` mais celle pour retirer est dans `controllerBasket` ?

2024-11-21 10:31 UTC, CarteSD commented on src/controllers/controllerBasket.class.php
> +     * @brief Permet de supprimer un article au panier
supprimer un article **du** panier

2024-11-21 10:31 UTC, CarteSD commented on src/models/article.dao.php
> +        $stmt->setFetchMode(PDO::FETCH_ASSOC);
Si tu fais un `FETCH_ASSOC`, le `fetch()` te renverra un tableau, il faut donc appliquer un hydrate car sinon ça retournera un tableau et non pas un objet du type `Article` à la fin.

2024-11-21 10:31 UTC, CarteSD commented on src/templates/basket.twig
> +{#                {% if articles is null %}#}
Enlever le commentaire

2024-11-21 10:31 UTC, CarteSD commented on src/templates/basket.twig
> +                    <p class="mt-2">Vous n'avez pas encore ajouté d'articles dans votre panier. Parcourez le site pour
```suggestion
                    <p class="mt-2">Vous n'avez pas encore ajouté d'article dans votre panier. Parcourez le site pour
```

2024-11-21 10:54 UTC, ConchezRob requested changes

2024-11-21 10:54 UTC, ConchezRob commented on public/assets/js/basket.js
Manque les commentaires sur la plus part des fonctions

2024-11-21 10:54 UTC, ConchezRob commented on public/assets/js/shop.js
> +
illisible

2024-11-21 10:54 UTC, ConchezRob commented on src/controllers/controllerBasket.class.php
> + * La classe ControllerBasket permet de faire le lien entre la vue et l'objet Basket
ajoute @brief

2024-11-27 13:11 UTC, TistouCode commented on public/assets/js/shop.js
> +                alert(xhr.responseText);  // Affiche la réponse (par exemple : "Article ajouté au panier !")
J'ai modif tqt, en revanche, La notion de "mocheté" est profondément subjective, car elle dépend des goûts, des cultures et des expériences personnelles de chaque individu. Ce qui peut paraître désagréable ou non conventionnel pour une personne peut être perçu comme unique, intrigant ou même beau pour une autre.

La perception de la beauté ou de la mocheté repose sur des standards sociaux et culturels qui varient selon les époques et les régions du monde. Par exemple, certaines caractéristiques physiques considérées comme attirantes dans une culture peuvent être jugées moins esthétiques dans une autre. Les médias, les normes sociales et les tendances jouent également un rôle majeur dans la construction de ces critères, souvent arbitraires.

Au-delà des apparences, la subjectivité de la mocheté réside dans la façon dont nous associons nos émotions et nos expériences à ce que nous voyons. Un visage, une œuvre d’art ou même un paysage que quelqu’un juge "moche" peut susciter chez une autre personne des sentiments de nostalgie, d’admiration ou d’empathie, simplement en raison de souvenirs ou de valeurs personnelles.

Enfin, il est important de se rappeler que chaque être humain possède une richesse et une singularité qui dépassent les jugements esthétiques. En embrassant cette diversité, nous pouvons apprendre à voir la beauté dans des formes et des expressions variées, même dans celles qui nous semblent, à première vue, inhabituelles.

Ainsi, la "mocheté" n’est pas une vérité universelle, mais une interprétation. Elle nous invite à questionner nos propres préjugés et à élargir notre regard sur le monde qui nous entoure.

Merci Lucas

2024-11-27 13:12 UTC, TistouCode commented on src/models/article.dao.php
> +    function findArticlesWithIds($ids)
ok

2024-11-27 13:14 UTC, TistouCode commented on src/models/article.dao.php
> +            $type = "Banner";
Oui or j'ai eu des problèmes dont nous discuterons dessus, par exemple avec un type Enum, dans le js le type enum est considéré comme "TYPE::Banner" ce qui est embetant quand je le traite dans le js, si je remet comme avant c'est embetant

2024-11-27 13:16 UTC, TistouCode commented on src/routes.php
> +    throw new Exception("Merci de renseigner une adresse e-mail et un mot de passe valides");
Roh c'est bon on fait tous des erreurs pas besoin de faire le choqué

2024-11-27 13:17 UTC, TistouCode commented on src/routes.php
> +    throw new Exception("Merci de renseigner une adresse e-mail et un mot de passe valides");
Même réponse que j'ai fait à lucas, on fait tous des erreurs et des ctrl v ctrl c foireux

2024-11-27 13:30 UTC, TistouCode commented on src/controllers/controllerBasket.class.php
> +                $article = $managerArticle->findArticlesWithIds( array($id_article) );
My bad

2024-11-27 13:32 UTC, TistouCode commented on src/templates/basket.twig
> +                                    <p class="text-right">{{ article.pricePoint }} Cms</p>
yes je suis dacc

2024-11-27 13:33 UTC, TistouCode commented on public/assets/js/shop.js
> +
Apprend à lire

2024-11-28 07:09 UTC, TistouCode commented on src/models/article.class.php
> +    private ?string $type;
Oui mais plus complexe dans le traitement

2024-11-28 08:08 UTC, lucas-luchack requested changes

2024-11-28 08:08 UTC, lucas-luchack commented on tailwind.config.js
> +  content: ["./src/**/*.{js,html,php,twig}", "./public/**/*.{js,html,php,twig,css}"],
```suggestion
  content: ["./src/**/*.{js,html,php,twig}"],
```

2024-11-28 09:17 UTC, CarteSD requested changes

2024-11-28 09:17 UTC, CarteSD commented on public/assets/js/basket.js
> +function removeArticle(id){
Manque la documentation du paramètre

2024-11-28 09:17 UTC, CarteSD commented on public/assets/js/shop.js
> + */
Mettre la documentation Doxygen

2024-11-28 09:17 UTC, CarteSD commented on public/assets/js/shop.js
> +
Enlever tous les retours à la ligne inutiles

2024-11-28 09:17 UTC, CarteSD commented on src/controllers/controllerBasket.class.php
> +    /**
```suggestion
    }
    
    /**
```

2024-11-28 10:55 UTC, CarteSD commented on src/controllers/controllerShop.class.php
Pourquoi on a deux méthodes qui font la même chose ? `show()` et `showAll()`

2024-11-28 17:52 UTC, lucas-luchack commented on src/controllers/controllerBasket.class.php
> +
Manque le namespace *(cf. doc)*

2024-11-29 13:34 UTC, lucas-luchack requested changes

2024-11-29 13:34 UTC, lucas-luchack commented on public/assets/js/basket.js
> + * @brief Permet de vérifier s'il reste des articles dans la panier, si oui, alors ne rien faire, si non alors afficher que la panier est vide
```suggestion
 * @brief Permet de vérifier s'il reste des articles dans la panier, si oui, alors ne rien faire, si non alors afficher que le panier est vide
```

2024-11-29 13:34 UTC, lucas-luchack commented on public/assets/js/basket.js
> +        console.log("pas d'articles")
Retirer les console.log

2024-11-29 13:34 UTC, lucas-luchack commented on public/assets/js/basket.js
> +        console.log("articles")
Idem

2024-11-29 13:34 UTC, lucas-luchack commented on public/assets/js/shop.js
> +    console.log(nbrArticles)
Idem

2024-11-29 13:34 UTC, lucas-luchack commented on src/controllers/controllerBasket.class.php
> + */
À mettre avant les use

2024-11-29 13:34 UTC, lucas-luchack commented on src/controllers/controllerBasket.class.php
> +use models\NotFoundException;
N'existe pas

2024-11-29 15:49 UTC, CarteSD commented on public/assets/js/basket.js
> + */
```suggestion
/**
 * @brief Vérifie le contenu du panier
 * @details Si le panier ne contient aucun article, affiche un message indiquant que celui-ci est vide.
 */
```

2024-11-29 15:54 UTC, lucas-luchack submitted a review, later dismissed

2024-11-29 15:54 UTC, lucas-luchack commented on src/templates/basket.twig
> +        <div class="flex flex-col w-2/3 h-min mt-5 ml-5">
C'est quoi `h-min` ?

2024-11-29 15:56 UTC, CarteSD requested changes

2024-11-29 15:56 UTC, CarteSD commented on public/assets/js/shop.js
> +    console.log( nbrArticles)
Enlever le `console.log`

2024-11-29 15:56 UTC, CarteSD commented on public/assets/js/shop.js
> + */
Raccourcir, c'est trop long pour une balise `brief`

2024-11-29 15:56 UTC, CarteSD commented on public/assets/js/shop.js
> + * @param article L'article qui doit être afficher dans la fenêtre modale
```suggestion
 * @param article L'article qui doit être affiché dans la fenêtre modale
```

2024-11-29 15:59 UTC, lucas-luchack submitted a review, later dismissed

2024-12-03 15:50 UTC, lucas-luchack requested changes

2024-12-03 15:50 UTC, lucas-luchack commented on public/assets/js/shop.js
> + * @brief    Le fichier contient le JS nécessaire au bon fonctionnement de la page basket
```suggestion
 * @brief   Le fichier contient le JS nécessaire au bon fonctionnement de la page basket
```
Espace en trop

2024-12-04 08:26 UTC, ConchezRob submitted a review, later dismissed

2024-12-04 17:01 UTC, lucas-luchack submitted a review, later dismissed

2024-12-04 17:04 UTC, ConchezRob requested changes

2024-12-04 17:04 UTC, ConchezRob commented on src/Models/article.class.php
> +    public function __construct(?int $id = null, ?DateTime $createdAt = null, ?DateTime $updatedAt = null, ?string $name = null, ?ArticleType $type = null, ?string $description = null , ?int $pricePo
priceEuro en float espèce de fils de pgfEZIYK

2024-12-04 17:15 UTC, ConchezRob approved these changes

2024-12-04 17:17 UTC, CarteSD approved these changes

2024-12-04 17:17 UTC, merged