💥 Ajout des Namespaces
ValbionGroup/Comus-Party pull request #44
Opened 2024-11-21 16:25 UTC by lucas-luchack

2024-11-21 16:30 UTC, CarteSD commented on src/Models/Exceptions/ErrorHandler.php
> +    public static function displayPopUpError(Exception $exception): void
Voir pour modifier le nom de la méthode puisqu'elle n'affiche pas à proprement parlé l'erreur, mais ajoute l'erreur en global afin que la template puisse par la suite afficher cette erreur.

2024-11-21 16:32 UTC, CarteSD requested changes

2024-11-21 16:32 UTC, CarteSD commented on src/Models/Exceptions/MalformedRequestException.php
> +
Manque la documentation du fichier

2024-11-21 16:32 UTC, CarteSD commented on src/Models/Exceptions/MalformedRequestException.php
> +class MalformedRequestException extends Exception
Manque la documentation de la classe

2024-11-21 16:50 UTC, CarteSD approved these changes

2024-11-21 16:50 UTC, CarteSD commented on src/Models/Exceptions/ErrorHandler.php
> +class ErrorHandler
Manque la documentation de la class (j'avais pas vu au premier passage my bad)

2024-11-21 16:55 UTC, CarteSD submitted a review, later dismissed

2024-11-22 09:15 UTC, ConchezRob approved these changes

2024-11-22 09:47 UTC, merged