[CP-71] Vérification et envoi au SIB
ValbionGroup/Comus-Party pull request #57
Opened 2024-12-02 15:07 UTC by CarteSD

2024-12-02 15:27 UTC, lucas-luchack requested changes

2024-12-02 15:27 UTC, lucas-luchack commented on src/Models/article.dao.php
> +            throw new UnauthorizedAccessException('Vous n\'avez pas accès à cette facture.');
```suggestion
            throw new NotFoundException('Cette facture n\'existe pas.');
```

2024-12-02 15:27 UTC, lucas-luchack commented on src/Models/invoice.dao.php
Peut-être rajouter une fonction pour récupérer les articles ?

2024-12-02 15:30 UTC, CarteSD commented on src/Models/invoice.dao.php
Il en existe déjà une dans la classe `ArticleDAO`.

Pour l'instant, l'attribut `articles` dans la classe `Invoice` est inutilisé, mais j'ai préféré le mettre si un jour nous en avons besoin (notamment avec l'implémentation d'une fonction telle)

2024-12-03 14:21 UTC, lucas-luchack submitted a review, later dismissed

2024-12-03 15:45 UTC, lucas-luchack submitted a review, later dismissed

2024-12-03 18:07 UTC, lucas-luchack commented on src/Models/invoice.class.php
> +enum paymentType
```suggestion
enum PaymentType
```

2024-12-03 18:08 UTC, lucas-luchack commented on tests/InvoiceTest.php
> +use ComusParty\Models\paymentType;
```suggestion
use ComusParty\Models\PaymentType;
```

2024-12-03 18:08 UTC, lucas-luchack commented on tests/InvoiceTest.php
> +            paymentType: paymentType::Card,
```suggestion
            paymentType: PaymentType::Card,
```

2024-12-03 18:18 UTC, CarteSD commented on src/Models/invoice.class.php
> +enum paymentType
Good ✅

2024-12-03 18:18 UTC, CarteSD commented on tests/InvoiceTest.php
> +use ComusParty\Models\paymentType;
Good ✅

2024-12-03 18:18 UTC, CarteSD commented on tests/InvoiceTest.php
> +            paymentType: paymentType::Card,
Good ✅

2024-12-04 07:23 UTC, lucas-luchack approved these changes

2024-12-04 07:27 UTC, ConchezRob approved these changes

2024-12-10 09:44 UTC, merged