Features/suppression du compte
ValbionGroup/Comus-Party pull request #64
Opened 2024-12-04 17:49 UTC by CarteSD

2024-12-09 12:04 UTC, lucas-luchack approved these changes

2024-12-09 20:49 UTC, lucas-luchack requested changes

2024-12-09 20:49 UTC, lucas-luchack commented on src/Controllers/controller.class.php
> +            }
La logique avec le `$e->getCode()` n'est pas bonne car pas assez précise.
Utiliser plutôt les nom des exceptions :
```suggestion
            switch ($e::class) {
                case AuthenticationException::class:
                    ErrorHandler::addExceptionParametersToSession($e);
                    header('Location: /login');
                    break;
                default:
                    ErrorHandler::displayFullScreenException($e);
                    break;
            }
```

2024-12-09 20:49 UTC, lucas-luchack commented on src/Controllers/controller.class.php
> +            }
Il faut que je vérif le reste du traitement de l'exception.
Mais je pense que le mieux est que tu mettes un @todo pour y penser plus tard.

2024-12-10 14:26 UTC, lucas-luchack approved these changes

2024-12-12 07:43 UTC, ConchezRob approved these changes

2024-12-13 08:14 UTC, TistouCode commented on src/templates/profil.twig
> +                    En accord avec nos <a href="/cgu">conditions d'utilisation</a> compte ne peut pas être supprimé
Il manque pas un "votre" avant le "compte ne peut pas être supprimé"

2024-12-13 08:15 UTC, TistouCode requested changes
Bien dans la globalité

2024-12-13 08:31 UTC, lucas-luchack approved these changes

2024-12-13 10:07 UTC, TistouCode approved these changes

2024-12-13 10:07 UTC, merged