[CP-70] Formulaire de paiement
ValbionGroup/Comus-Party pull request #66
Opened 2024-12-10 13:29 UTC by ConchezRob

2024-12-10 14:05 UTC, CarteSD requested changes

2024-12-10 14:05 UTC, CarteSD commented on src/templates/checkout.twig
> +                    <li class="flex items-center w-full after:border-b after:border-1 after:mx-2 after:my-0 after:hidden after:border-white after:w-full sm:after:inline-block after:content-['']">
Gérer le thème sombre / clair au niveau de la barre qui sépare chacun des éléments

2024-12-16 10:07 UTC, nzoEtd commented
Actuellement l'bouton pour payer est disponible même si le panier est vide, peut-être interdire de payer dans ce cas là.
J'pense qu'il faut approcher ça en vérifiant le contenu du panier, pas si le total du prix vaut 0, puisqu'on pourraît peut-être faire en sorte plus tard que des items soient à acheter mais avec un prix de 0 (stratégie fréquente pour forcer le joueur à intéragir avec le shop, et donc le rendre plus susceptible d'acheter puisqu'il a conscience qu'il existe et est déjà familier avec)

2024-12-16 18:13 UTC, lucas-luchack submitted a review, later dismissed

2024-12-17 07:23 UTC, CarteSD commented
![image](https://github.com/user-attachments/assets/4af08bf4-f2fc-46ea-9695-ea9c5a06ae46)

Il n'y a pas de gestion des caractères spéciaux dans le nom

2024-12-17 07:30 UTC, CarteSD submitted a review, later dismissed
Ajouter la gestion des caractères spéciaux pour le nom

2024-12-17 11:22 UTC, CarteSD submitted a review, later dismissed
Robin CONCHEZ-BOUEYTOU est un élève sérieux et investi dans son travail. Ses résultats sont satisfaisants, et il montre une bonne capacité à assimiler les notions abordées en classe. Il participe régulièrement et fait preuve de curiosité, ce qui est encourageant. Quelques efforts supplémentaires en responsive lui permettraient d'améliorer encore son niveau et de pleinement exploiter son potentiel. Nous l’encourageons à continuer sur cette voie et à développer davantage sa régularité.

2024-12-17 14:36 UTC, nzoEtd commented on src/templates/checkout.twig
> +                                <span>Nom complet</span>
Préciser que "Nom complet" veut dire nom et prénom. Il faut obligatoirement un espace dans le champ, donc changer le texte dans le span (Nom complet) et le placeholder de l'input (Nom complet) en donnant un exemple (ex: Robin Lamoula)

2024-12-17 14:36 UTC, nzoEtd commented on public/assets/js/checkout.js
> +}
Traduire tous les commentaires j'suis pas très fort en anglais désolé.
Aussi, rajouter la doc des fonction (au dessus de chacune)

2024-12-17 15:34 UTC, ConchezRob commented on public/assets/js/checkout.js
> +}
T'as qu'à être meilleur

2024-12-17 15:41 UTC, CarteSD requested changes
"Nom Prénom" => "Nom complet" + modifier le placeholder

2024-12-17 15:43 UTC, CarteSD approved these changes

2024-12-17 15:54 UTC, lucas-luchack approved these changes

2024-12-17 15:54 UTC, merged