[CP-38] Modifier son avatar
ValbionGroup/Comus-Party pull request #78
Opened 2024-12-18 10:56 UTC by TistouCode

2024-12-18 13:51 UTC, CarteSD requested changes

2024-12-18 15:49 UTC, TistouCode commented on src/css/base.css
> +}
Je m'en sert pour trouver l'image actuellement select donc non je l'enlève pas

2024-12-18 15:59 UTC, ConchezRob approved these changes

2024-12-19 08:04 UTC, CarteSD requested changes
![image](https://github.com/user-attachments/assets/879e396c-f961-4585-b9d8-cd63f1f1a2c6)

La photo de quoi ?

2024-12-19 08:05 UTC, CarteSD requested changes

2024-12-19 08:05 UTC, CarteSD commented on src/Models/article.dao.php
> +    /**
```suggestion
        $_SESSION['pfpPath'] = $article->getFilePath();
    }
    
    /**
```

2024-12-19 10:53 UTC, lucas-luchack requested changes

2024-12-19 10:53 UTC, lucas-luchack commented on src/css/base.css
> +}
Fonctionne autrement alors

2024-12-19 10:53 UTC, lucas-luchack commented on src/routes.php
> +    }
Si le `main` est récupéré, ce n'est plus utile.

```suggestion
```

2024-12-19 10:53 UTC, lucas-luchack commented on src/templates/profil.twig
Vérifier que le responsive fonctionne.
Si oui, c'est nickel.

2024-12-20 10:49 UTC, lucas-luchack approved these changes

2024-12-20 11:00 UTC, CarteSD requested changes

2024-12-20 11:00 UTC, CarteSD commented on src/Models/article.dao.php
> +        WHERE i.player_uuid = :uuid AND ir.invoice_id = :idArticleActif');
```suggestion
        WHERE i.player_uuid = :uuid AND ir.article_id= :idArticleActif');
```

2024-12-20 11:01 UTC, lucas-luchack approved these changes

2024-12-20 11:03 UTC, merged