features/Connection-Moderateur
ValbionGroup/Comus-Party pull request #79
Opened 2024-12-18 11:08 UTC by ConchezRob

2024-12-18 13:31 UTC, CarteSD commented on src/Models/moderator.class.php
> +    private ?DateTime $updatedAt;
Ajouter un retour à la ligne pour séparer chaque attribut

2024-12-18 13:31 UTC, CarteSD commented on src/Models/moderator.class.php
> +     * @param DateTime|null $updatedAt
Documenter chacun des paramètres

2024-12-18 13:32 UTC, CarteSD commented on src/Models/moderator.class.php
Pour les getters, documenter ce à quoi correspond les types retournés

2024-12-18 15:17 UTC, lucas-luchack requested changes

2024-12-18 15:17 UTC, lucas-luchack commented on src/Models/moderator.class.php
> +    private ?DateTime $updatedAt;
```suggestion
    /**
     * @brief L'UUID du modérateur, identifiant unique
     * @var string|null UUID
     */
    private ?string $uuid;

    /**
     * @brief L'identifiant de l'utilisateur associé au modérateur
     * @var int|null Identifiant de l'utilisateur lié
     */
    private ?int $userId;

    /**
     * @brief Le prénom du modérateur
     * @var string|null Prénom
     */
    private ?string $firstName;

    /**
     * @brief Le nom de famille du modérateur
     * @var string|null Nom de famille
     */
    private ?string $lastName;

    /**
     * @brief La date de création du profil de modérateur
     * @var DateTime|null Date de création
     */
    private ?DateTime $createdAt;

    /**
     * @brief La date de mise à jour du profil de modérateur
     * @var DateTime|null Date de mise à jour
     */
    private ?DateTime $updatedAt;
```

2024-12-19 07:41 UTC, CarteSD submitted a review, later dismissed

2024-12-19 09:07 UTC, CarteSD submitted a review, later dismissed

2024-12-19 10:35 UTC, lucas-luchack submitted a review, later dismissed

2024-12-19 10:47 UTC, lucas-luchack approved these changes

2024-12-19 10:54 UTC, lucas-luchack approved these changes

2024-12-19 11:00 UTC, CarteSD approved these changes

2024-12-19 11:00 UTC, merged