[CP-30] Ajout des classes `GameRecord`
ValbionGroup/Comus-Party pull request #88
Opened 2024-12-20 10:35 UTC by lucas-luchack

La suite arrivera plus tard mais je fait cette PR en premier.

2024-12-20 10:47 UTC, CarteSD requested changes

2024-12-20 10:47 UTC, CarteSD commented on src/Models/gamerecord.dao.php
> +     * @brief Retourne la liste des parties
Mauvaise documentation

2024-12-20 10:47 UTC, CarteSD commented on src/Models/gamerecord.dao.php
> +     * @brief Retourne la liste des parties
Mauvaise documentation

2024-12-20 10:47 UTC, CarteSD commented on tests/GameRecordTest.php
> +     * @brief The game record to test
In french please

2024-12-20 11:14 UTC, CarteSD submitted a review, later dismissed

2024-12-23 14:32 UTC, CarteSD requested changes

2024-12-23 14:32 UTC, CarteSD commented on src/Models/gameRecord.dao.php
> +     * @brief Constructeur de la classe UserDAO
```suggestion
     * @brief Constructeur de la classe GameRecordDAO
```

2024-12-23 14:32 UTC, CarteSD commented on src/Models/gameRecord.dao.php
> +     * @brief Retourne la liste des parties grâce à l'ID du joueur
```suggestion
     * @brief Retourne la liste des joueurs dans une partie grâce à l'UUID de celle-ci
```

2024-12-23 14:32 UTC, CarteSD commented on src/Models/gameRecord.dao.php
> +     * @param string $uuid L'UUID de la partie recherchée
```suggestion
     * @param string $uuid L'UUID du joueur ayant hébergé les parties
```

2024-12-23 14:32 UTC, CarteSD commented on src/Models/gameRecord.dao.php
> +     * @brief Retourne un tableau d'objets GameRecord (ou null) à partir de l'UUID passé en paramètre
```suggestion
     * @brief Retourne un tableau d'objets GameRecord (ou null) à partir de l'UUID passé en paramètre correspondant aux parties hébergées par un joueur
```

2024-12-23 14:32 UTC, CarteSD commented on src/Models/gameRecord.dao.php
> +     * @brief Retourne un objet GameRecord (ou null) à partir de l'ID passé en paramètre
```suggestion
     * @brief Retourne un tableau d'objets GameRecord (ou null) à partir de l'état passé en paramètre
```

2024-12-23 14:32 UTC, CarteSD commented on src/Models/gameRecord.dao.php
> +     * @param GameRecordState $state L'état de la partie recherchée
```suggestion
     * @param GameRecordState $state L'état des parties recherchées
```

2024-12-24 16:01 UTC, ConchezRob approved these changes

2024-12-24 16:22 UTC, CarteSD approved these changes

2024-12-24 16:22 UTC, merged