[CP-39] Modifier sa bannière
ValbionGroup/Comus-Party pull request #92
Opened 2024-12-26 10:40 UTC by TistouCode

2024-12-26 11:41 UTC, CarteSD requested changes
J'suis un peu perturbé par le fait que le type de l'article est passé en paramètre dans un peu toutes les fonctions et toutes les requêtes alors qu'à partir de son ID on peut connaître le type.

Je pense qu'on a moyen d'optimiser ça car t'as sûrement dû voir que c'est juste de la duplication de code pour les deux types d'articles.

Pour l'instant on peut laisser comme ça car on a pas trop de temps à perdre, mais il faudrait qu'on y repasse plus tard

2024-12-26 11:41 UTC, CarteSD commented on public/assets/js/profil.js
> +    console.log(typeArticle)
À enlever

2024-12-26 11:41 UTC, CarteSD commented on public/assets/js/profil.js
> +            console.log(response)
À enlever aussi

2024-12-26 11:41 UTC, CarteSD commented on src/Controllers/controllerProfile.class.php
> +    public function updateStyle(?string $player_uuid, string $idArticle, string $typeArticle): void
Mettre à jour la doc' suite au nouveau paramètre

2024-12-26 11:41 UTC, CarteSD commented on src/Controllers/controllerProfile.class.php
> +                'typeArticle' => $typeArticle,
Je ne sais pas si c'est utile de renvoyer le type de l'article étant donné que tu le connais déjà

2024-12-26 11:41 UTC, CarteSD commented on src/Controllers/controllerProfile.class.php
> +    private $deleteActiveArticleForPfp;
Pourquoi ? Tu ne l'utilises nul part

2024-12-26 11:41 UTC, CarteSD commented on src/Models/article.dao.php
> +    public function updateActiveArticle(string $uuid, string $idArticle, string $typeArticle)
Idem, mettre à jour la doc'

2024-12-27 14:02 UTC, TistouCode commented on src/Controllers/controllerProfile.class.php
> +    private $deleteActiveArticleForPfp;
Si, dans ControllerProfile à la ligne 138 et 145

2024-12-27 14:03 UTC, TistouCode commented on src/Controllers/controllerProfile.class.php
> +    private $deleteActiveArticleForPfp;
Je pourrais les opti pour en faire qu'un j'avoue mais la je suis dans le bus et j'ai la flemme

2024-12-27 16:34 UTC, CarteSD commented on src/Controllers/controllerProfile.class.php
> +    private $deleteActiveArticleForPfp;
![image](https://github.com/user-attachments/assets/3e10915e-1870-45c7-b5af-0b14e6f717cc)

![image](https://github.com/user-attachments/assets/4ceeb56c-42f3-42ec-9896-1c17a1554099)

2024-12-27 16:41 UTC, CarteSD commented
![image](https://github.com/user-attachments/assets/f39ef207-d058-4998-847f-04ab03a9261c)

J'ai un autre problème chef (et je n'ai aucune idée de l'endroit d'où il peut venir)

2024-12-29 14:54 UTC, lucas-luchack commented
@CarteSD, normalement maintenant c'est OK tu devrais plus avoir le problème

2024-12-29 15:00 UTC, CarteSD commented
> @CarteSD, normalement maintenant c'est OK tu devrais plus avoir le problème

T'es chaud t'es chaud

2024-12-29 15:03 UTC, CarteSD submitted a review, later dismissed
Mise à part les premières remarques d'optimisation précédemment, c'est good

2024-12-30 11:17 UTC, lucas-luchack requested changes

2025-01-02 21:16 UTC, lucas-luchack approved these changes

2025-01-03 11:06 UTC, CarteSD approved these changes

2025-01-06 13:12 UTC, merged