[CP-30] Lancer une partie
ValbionGroup/Comus-Party pull request #93
Opened 2024-12-26 15:44 UTC by lucas-luchack

**A BESOIN DE LA CP-29 DANS LE `main` POUR POUVOIR ÊTRE MERGE**
*Cette PR est donc en brouillon le temps que l'autre soit acceptée*

2024-12-27 09:56 UTC, CarteSD commented
Je pense qu'un autre membre pourrait essayer de faire un message d'erreur dynamique si jamais les conditions de lancement de la partie ne sont pas respectées

2024-12-27 09:58 UTC, CarteSD commented on games/README.md
J'adore !

2024-12-27 10:03 UTC, CarteSD submitted a review, later dismissed
C'est du très bon boulot, juste à voir ce qu'on choisit entre `uuid` et `code` pour l'identificateur d'une partie

2024-12-27 10:03 UTC, CarteSD commented on src/Models/gameRecord.dao.php
> +     * @brief Retourne la liste des joueurs dans une partie grâce à l'UUID de celle-ci
Si on met `code`, il faut le remplacer ici aussi

2024-12-27 10:14 UTC, lucas-luchack commented on src/Controllers/controllerGame.class.php
> +     * @param string $code Code de la partie
Oui, mais il faut changer partout même en base de données

2024-12-27 12:07 UTC, lucas-luchack commented
> Je pense qu'un autre membre pourrait essayer de faire un message d'erreur dynamique si jamais les conditions de lancement de la partie ne sont pas respectées

Effectivement, c'est à faire, je comptais le faire aussi mais si quelqu'un d'autre veux s'en charger c'est sans problème.

2024-12-27 12:16 UTC, CarteSD commented
> > Je pense qu'un autre membre pourrait essayer de faire un message d'erreur dynamique si jamais les conditions de lancement de la partie ne sont pas respectées
> 
> Effectivement, c'est à faire, je comptais le faire aussi mais si quelqu'un d'autre veux s'en charger c'est sans problème.

Il faut que quelqu'un d'autre le fasse, ça peut nous permettre de nous imprégner du fonctionnement et de l'interaction entre les différents fichiers comme ça

2024-12-27 12:18 UTC, CarteSD approved these changes

2024-12-30 10:16 UTC, CarteSD approved these changes

2024-12-30 10:16 UTC, CarteSD commented on src/App/Exceptions/PaymentException.php
> +     * @param Throwable|null $previous Exceptionprécédente
?

2024-12-30 10:24 UTC, CarteSD requested changes

2024-12-30 10:24 UTC, CarteSD commented on src/App/MessageHandler.php
> +     * @param Exception $exception Exceptions à afficher
Aïe le Refactor qui s'est planté
```suggestion
     * @param Exception $exception Exception à afficher
```

2024-12-30 10:24 UTC, CarteSD commented on src/App/MessageHandler.php
> +     * @param Exception $exception Exceptions à afficher
```suggestion
     * @param Exception $exception Exception à afficher
```

2024-12-30 10:24 UTC, CarteSD commented on src/Controllers/controller.class.php
> +     * @throws MethodNotFoundException Exceptions levée dans le cas où la méhode n'existe pas
```suggestion
     * @throws MethodNotFoundException Exception levée dans le cas où la méhode n'existe pas
```

2024-12-30 10:24 UTC, CarteSD commented on src/Controllers/controllerAuth.class.php
Enlever tous les -s à Exception

2024-12-30 10:24 UTC, CarteSD commented on src/Controllers/controllerBasket.class.php
Enlever tous les -s à Exception dans la documentation

2024-12-30 10:24 UTC, CarteSD commented on src/Controllers/controllerDashboard.class.php
Enlever tous les -s à Exception dans la documentation

2024-12-30 10:24 UTC, CarteSD commented on src/Controllers/controllerFactory.class.php
> +     * @throws ControllerNotFoundException Exceptions levée dans le cas où le contrôleur n'est pas trouvé
```suggestion
     * @throws ControllerNotFoundException Exception levée dans le cas où le contrôleur n'est pas trouvé
```

2024-12-30 10:24 UTC, CarteSD commented on src/Controllers/controllerGame.class.php
Enlever tous les -s à Exception dans la documentation

2024-12-30 10:24 UTC, CarteSD commented on src/Controllers/controllerPolicy.class.php
Enlever tous les -s à Exception dans la documentation

2024-12-30 10:24 UTC, CarteSD commented on src/Controllers/controllerProfile.class.php
Enlever tous les -s à Exception dans la documentation

2024-12-30 10:24 UTC, CarteSD commented on src/Controllers/controllerShop.class.php
Enlever tous les -s à Exception dans la documentation

2024-12-30 10:24 UTC, CarteSD commented on src/Models/article.dao.php
Enlever tous les -s à Exception dans la documentation

2024-12-30 10:24 UTC, CarteSD commented on src/Models/db.class.php
> +     * @throws Exception Exceptions levée dans le cas d'une tentative de désérialisation
```suggestion
     * @throws Exception Exception levée dans le cas d'une tentative de désérialisation
```

2024-12-30 10:24 UTC, CarteSD commented on src/Models/gameRecord.dao.php
> +     * @throws Exception Exceptions levée en cas d'erreur lors de l'hydratation
```suggestion
     * @throws Exception Exception levée en cas d'erreur lors de l'hydratation
```

2024-12-30 10:24 UTC, CarteSD commented on src/Models/invoice.dao.php
Enlever tous les -s à Exception dans la documentation

2024-12-30 10:24 UTC, CarteSD commented on src/Models/moderator.dao.php
> +     * @throws DateMalformedStringException Exceptions levée dans le cas d'une date malformée
```suggestion
     * @throws DateMalformedStringException Exception levée dans le cas d'une date malformée
```

2024-12-30 10:24 UTC, CarteSD commented on src/Models/passwordResetToken.dao.php
Enlever tous les -s à Exception dans la documentation

2024-12-30 10:24 UTC, CarteSD commented on src/Models/player.dao.php
Enlever tous les -s à Exception dans la documentation

2024-12-30 10:24 UTC, CarteSD commented on src/Models/suggestion.dao.php
Enlever tous les -s à Exception dans la documentation

2024-12-30 10:24 UTC, CarteSD commented on src/Models/user.dao.php
Enlever tous les -s à Exception dans la documentation

2024-12-30 19:31 UTC, CarteSD approved these changes

2025-01-07 11:27 UTC, CarteSD approved these changes

2025-01-07 12:42 UTC, merged